### ISSUE TITLE
Can you give me an example of doscar?

### ISSUE THREAD

**Issue by Wangpaipai** [bjmorgan/vasppy#13] opened 2020-07-06 03:09 UTC
Hello,I had an error creating the Doscar object,
The error message is "ValueError: cannot reshape array of size 0 into shape (2,301,9,2)",
Can you give me an example of doscar?
Thank you!

**Comment by Wangpaipai** [comment] 2020-07-06 04:30
`from vasppy.doscar import Doscar
ds = Doscar("DOSCAR")`
The code creates only one doscar object, which is wrong

**Comment by bjmorgan** [comment] 2020-07-06 10:56
```python
from vasppy.doscar import Doscar
ds = Doscar("DOSCAR")
```
Can you explain what behaviour were you expecting?
The intended behaviour is to return a single `Doscar` object, as indicated in the docstring for `Doscar.__init__()`:
```python
    def __init__(…):
        '''
        Create a Doscar object from a VASP DOSCAR file.
        …
        '''

```

**Comment by Wangpaipai** [comment] 2020-07-07 01:39
I hope that through pdos_select() to get the density of states array,But there was an error creating the object.
`
from vasppy.doscar import Doscar
ds = Doscar("DOSCAR")
density_state_arr = ds.pdos_select()
`

**Comment by bjmorgan** [comment] 2020-07-07 06:30
Can you please post your code example verbatim, and the error you get when running it?

**Comment by Wangpaipai** [comment] 2020-07-07 08:31
![1594110557(1)](https://user-images.githubusercontent.com/28752345/86748512-1980dd80-c06f-11ea-877e-02b4a64a0124.jpg)

**Comment by Wangpaipai** [comment] 2020-07-07 08:33
The contents of the OUTCAR file are as follows

   2   2   0   0
  0.8911265E+01  0.2612100E-09  0.2612100E-09  0.2612100E-09  0.1000000E-15
  1.000000000000000E-004
  CAR 
 Fe                                      
     27.91029730     -6.40770673  301      5.43173395      1.00000000
     -6.408  0.0000E+00  0.0000E+00  0.0000E+00  0.0000E+00
     -6.293  0.0000E+00  0.0000E+00  0.0000E+00  0.0000E+00
     -6.179  0.0000E+00  0.0000E+00  0.0000E+00  0.0000E+00
     -6.065  0.0000E+00  0.0000E+00  0.0000E+00  0.0000E+00
     -5.950  0.0000E+00  0.0000E+00  0.0000E+00  0.0000E+00
     -5.836  0.0000E+00  0.0000E+00  0.0000E+00  0.0000E+00
     -5.721 -0.1336E-37 -0.1336E-37 -0.1529E-38 -0.1529E-38
     -5.607 -0.1501E-29 -0.1501E-29 -0.1717E-30 -0.1717E-30
     -5.493 -0.1204E-22 -0.1204E-22 -0.1378E-23 -0.1378E-23
     -5.378 -0.6619E-17 -0.6619E-17 -0.7572E-18 -0.7572E-18
     -5.264 -0.2606E-12 -0.2606E-12 -0.2982E-13 -0.2982E-13
     -5.149 -0.7195E-09 -0.7195E-09 -0.8233E-10 -0.8233E-10
     -5.035 -0.1465E-06 -0.1465E-06 -0.1684E-07 -0.1684E-07
     -4.921 -0.1977E-05 -0.1977E-05 -0.2430E-06 -0.2430E-06
     -4.806  0.2136E-04  0.2136E-04  0.2201E-05  0.2201E-05
     -4.692  0.1116E-03  0.1116E-03  0.1497E-04  0.1497E-04
     -4.577  0.1375E-03  0.1375E-03  0.3070E-04  0.3070E-04
     -4.463  0.2618E-03  0.2618E-03  0.6065E-04  0.6065E-04
     -4.349  0.1510E-03  0.1510E-03  0.7793E-04  0.7793E-04
     -4.234  0.3310E-03  0.3310E-03  0.1158E-03  0.1158E-03
     -4.120  0.2841E-03  0.2841E-03  0.1483E-03  0.1483E-03
     -4.005  0.3410E-03  0.3410E-03  0.1873E-03  0.1873E-03
     -3.891  0.2772E-03  0.2772E-03  0.2190E-03  0.2190E-03
     -3.777  0.3937E-03  0.3937E-03  0.2640E-03  0.2640E-03
     -3.662  0.4525E-03  0.4525E-03  0.3158E-03  0.3158E-03
     -3.548  0.4721E-03  0.4721E-03  0.3698E-03  0.3698E-03
     -3.433  0.2574E-03  0.2574E-03  0.3993E-03  0.3993E-03
     -3.319  0.4676E-03  0.4676E-03  0.4528E-03  0.4528E-03
     -3.205  0.6234E-03  0.6234E-03  0.5241E-03  0.5241E-03
     -3.090  0.5581E-03  0.5581E-03  0.5879E-03  0.5879E-03
     -2.976  0.4231E-03  0.4231E-03  0.6363E-03  0.6363E-03
     -2.862  0.3862E-03  0.3862E-03  0.6805E-03  0.6805E-03
     -2.747  0.7691E-03  0.7691E-03  0.7685E-03  0.7685E-03
     -2.633  0.6110E-03  0.6110E-03  0.8384E-03  0.8384E-03
     -2.518  0.5017E-03  0.5017E-03  0.8958E-03  0.8958E-03
     -2.404  0.7098E-03  0.7098E-03  0.9769E-03  0.9769E-03
     -2.290  0.6637E-03  0.6637E-03  0.1053E-02  0.1053E-02
     -2.175  0.7471E-03  0.7471E-03  0.1138E-02  0.1138E-02
     -2.061  0.4974E-03  0.4974E-03  0.1195E-02  0.1195E-02
     -1.946  0.7718E-03  0.7718E-03  0.1284E-02  0.1284E-02
     -1.832  0.9603E-03  0.9603E-03  0.1393E-02  0.1393E-02
     -1.718  0.8085E-03  0.8085E-03  0.1486E-02  0.1486E-02
     -1.603  0.7279E-03  0.7279E-03  0.1569E-02  0.1569E-02
     -1.489  0.7592E-03  0.7592E-03  0.1656E-02  0.1656E-02
     -1.374  0.9768E-03  0.9768E-03  0.1768E-02  0.1768E-02
     -1.260  0.9464E-03  0.9464E-03  0.1876E-02  0.1876E-02
     -1.146  0.1271E-02  0.1271E-02  0.2021E-02  0.2021E-02
     -1.031  0.9481E-03  0.9481E-03  0.2130E-02  0.2130E-02
     -0.917  0.1048E-02  0.1048E-02  0.2250E-02  0.2250E-02
     -0.802  0.8028E-03  0.8028E-03  0.2341E-02  0.2341E-02
     -0.688  0.1368E-02  0.1368E-02  0.2498E-02  0.2498E-02
     -0.574  0.1031E-02  0.1031E-02  0.2616E-02  0.2616E-02
     -0.459  0.1079E-02  0.1079E-02  0.2739E-02  0.2739E-02
     -0.345  0.9403E-03  0.9403E-03  0.2847E-02  0.2847E-02
     -0.230  0.8629E-03  0.8629E-03  0.2946E-02  0.2946E-02
     -0.116  0.1449E-02  0.1449E-02  0.3111E-02  0.3111E-02
     -0.002  0.1180E-02  0.1180E-02  0.3246E-02  0.3246E-02
      0.113  0.1012E-02  0.1012E-02  0.3362E-02  0.3362E-02
      0.227  0.1108E-02  0.1108E-02  0.3489E-02  0.3489E-02
      0.342  0.1591E-02  0.1591E-02  0.3671E-02  0.3671E-02
      0.456  0.1579E-02  0.1579E-02  0.3851E-02  0.3851E-02
      0.570  0.4437E-02  0.4437E-02  0.4359E-02  0.4359E-02
      0.685  0.4623E-02  0.4623E-02  0.4888E-02  0.4888E-02
      0.799  0.3158E-02  0.3158E-02  0.5249E-02  0.5249E-02
      0.913  0.2806E-02  0.2806E-02  0.5570E-02  0.5570E-02
      1.028  0.1978E-02  0.1978E-02  0.5796E-02  0.5796E-02
      1.142  0.1927E-02  0.1927E-02  0.6017E-02  0.6017E-02
      1.257  0.2919E-02  0.2919E-02  0.6351E-02  0.6351E-02
      1.371  0.4555E-02  0.4555E-02  0.6872E-02  0.6872E-02
      1.485  0.4564E-02  0.4564E-02  0.7394E-02  0.7394E-02
      1.600  0.4599E-02  0.4599E-02  0.7920E-02  0.7920E-02
      1.714  0.6317E-02  0.6317E-02  0.8643E-02  0.8643E-02
      1.829  0.4258E-02  0.4258E-02  0.9130E-02  0.9130E-02
      1.943  0.5419E-02  0.5419E-02  0.9750E-02  0.9750E-02
      2.057  0.8141E-02  0.8141E-02  0.1068E-01  0.1068E-01
      2.172  0.7785E-02  0.7785E-02  0.1157E-01  0.1157E-01
      2.286  0.7128E-02  0.7128E-02  0.1239E-01  0.1239E-01
      2.401  0.7143E-02  0.7143E-02  0.1320E-01  0.1320E-01
      2.515  0.6872E-02  0.6872E-02  0.1399E-01  0.1399E-01
      2.629  0.4093E-02  0.4093E-02  0.1446E-01  0.1446E-01
      2.744  0.2184E-02  0.2184E-02  0.1471E-01  0.1471E-01
      2.858  0.3402E-02  0.3402E-02  0.1510E-01  0.1510E-01
      2.973  0.6901E-02  0.6901E-02  0.1589E-01  0.1589E-01
      3.087  0.9532E-02  0.9532E-02  0.1698E-01  0.1698E-01
      3.201  0.9512E-02  0.9512E-02  0.1807E-01  0.1807E-01
      3.316  0.7016E-02  0.7017E-02  0.1887E-01  0.1887E-01
      3.430  0.6493E-02  0.6493E-02  0.1961E-01  0.1961E-01
      3.545  0.1214E-01  0.1214E-01  0.2100E-01  0.2100E-01
      3.659  0.1304E-01  0.1304E-01  0.2249E-01  0.2249E-01
      3.773  0.1373E-01  0.1373E-01  0.2406E-01  0.2406E-01
      3.888  0.1166E-01  0.1166E-01  0.2540E-01  0.2540E-01
      4.002  0.1032E-01  0.1032E-01  0.2658E-01  0.2658E-01
      4.116  0.7930E-02  0.7930E-02  0.2748E-01  0.2748E-01
      4.231  0.5297E-02  0.5297E-02  0.2809E-01  0.2809E-01
      4.345  0.2547E-02  0.2547E-02  0.2838E-01  0.2838E-01
      4.460  0.2328E-02  0.2328E-02  0.2865E-01  0.2865E-01
      4.574  0.1516E-02  0.1516E-02  0.2882E-01  0.2882E-01
      4.688  0.2155E-02  0.2155E-02  0.2907E-01  0.2907E-01
      4.803  0.1401E-02  0.1401E-02  0.2923E-01  0.2923E-01
      4.917  0.3556E-03  0.3556E-03  0.2927E-01  0.2927E-01
      5.032  0.1122E-02  0.1122E-02  0.2940E-01  0.2940E-01
      5.146  0.8289E-03  0.8289E-03  0.2949E-01  0.2949E-01
      5.260  0.1299E-02  0.1299E-02  0.2964E-01  0.2964E-01
      5.375  0.1917E-02  0.1917E-02  0.2986E-01  0.2986E-01
      5.489  0.2660E-02  0.2660E-02  0.3016E-01  0.3016E-01
      5.604  0.3683E-02  0.3683E-02  0.3058E-01  0.3058E-01
      5.718  0.2231E-02  0.2231E-02  0.3084E-01  0.3084E-01
      5.832  0.1293E-02  0.1293E-02  0.3099E-01  0.3099E-01
      5.947  0.1934E-02  0.1934E-02  0.3121E-01  0.3121E-01
      6.061  0.2680E-02  0.2680E-02  0.3152E-01  0.3152E-01
      6.176  0.1626E-02  0.1626E-02  0.3170E-01  0.3170E-01
      6.290  0.1392E-02  0.1392E-02  0.3186E-01  0.3186E-01
      6.404  0.1296E-02  0.1296E-02  0.3201E-01  0.3201E-01
      6.519  0.1178E-02  0.1178E-02  0.3214E-01  0.3214E-01
      6.633  0.1484E-02  0.1484E-02  0.3231E-01  0.3231E-01
      6.748  0.1814E-02  0.1814E-02  0.3252E-01  0.3252E-01
      6.862  0.1523E-02  0.1523E-02  0.3270E-01  0.3270E-01
      6.976  0.7719E-03  0.7719E-03  0.3278E-01  0.3278E-01
      7.091  0.1663E-02  0.1663E-02  0.3297E-01  0.3297E-01
      7.205  0.9213E-03  0.9213E-03  0.3308E-01  0.3308E-01
      7.319  0.9521E-03  0.9521E-03  0.3319E-01  0.3319E-01
      7.434  0.8241E-03  0.8241E-03  0.3328E-01  0.3328E-01
      7.548  0.8728E-03  0.8728E-03  0.3338E-01  0.3338E-01
      7.663  0.1217E-02  0.1217E-02  0.3352E-01  0.3352E-01
      7.777  0.1370E-02  0.1370E-02  0.3368E-01  0.3368E-01
      7.891  0.1052E-02  0.1052E-02  0.3380E-01  0.3380E-01
      8.006  0.1050E-02  0.1050E-02  0.3392E-01  0.3392E-01
      8.120  0.7271E-03  0.7271E-03  0.3400E-01  0.3400E-01
      8.235  0.4046E-03  0.4046E-03  0.3405E-01  0.3405E-01
      8.349  0.2350E-03  0.2350E-03  0.3408E-01  0.3408E-01
      8.463  0.4545E-03  0.4545E-03  0.3413E-01  0.3413E-01
      8.578  0.8059E-03  0.8059E-03  0.3422E-01  0.3422E-01
      8.692  0.1084E-02  0.1084E-02  0.3434E-01  0.3434E-01
      8.807  0.1276E-02  0.1276E-02  0.3449E-01  0.3449E-01
      8.921  0.3669E-03  0.3669E-03  0.3453E-01  0.3453E-01
      9.035  0.3512E-03  0.3512E-03  0.3457E-01  0.3457E-01
      9.150  0.2336E-03  0.2336E-03  0.3460E-01  0.3460E-01
      9.264  0.2706E-03  0.2706E-03  0.3463E-01  0.3463E-01
      9.379  0.2017E-03  0.2017E-03  0.3465E-01  0.3465E-01
      9.493  0.2243E-03  0.2243E-03  0.3468E-01  0.3468E-01
      9.607  0.2561E-03  0.2561E-03  0.3471E-01  0.3471E-01
      9.722  0.3423E-03  0.3423E-03  0.3475E-01  0.3475E-01
      9.836  0.5724E-03  0.5724E-03  0.3481E-01  0.3481E-01
      9.951  0.5206E-03  0.5206E-03  0.3487E-01  0.3487E-01
     10.065  0.2895E-03  0.2895E-03  0.3490E-01  0.3490E-01
     10.179  0.4216E-03  0.4216E-03  0.3495E-01  0.3495E-01
     10.294  0.6360E-03  0.6360E-03  0.3503E-01  0.3503E-01
     10.408  0.3472E-03  0.3472E-03  0.3507E-01  0.3507E-01
     10.523  0.3814E-03  0.3814E-03  0.3511E-01  0.3511E-01
     10.637  0.1344E-02  0.1344E-02  0.3526E-01  0.3526E-01
     10.751  0.1641E-02  0.1641E-02  0.3545E-01  0.3545E-01
     10.866  0.2291E-02  0.2291E-02  0.3571E-01  0.3571E-01
     10.980  0.3648E-02  0.3648E-02  0.3613E-01  0.3613E-01
     11.094  0.3598E-02  0.3598E-02  0.3654E-01  0.3654E-01
     11.209  0.1837E-02  0.1837E-02  0.3675E-01  0.3675E-01
     11.323  0.1923E-02  0.1923E-02  0.3697E-01  0.3697E-01
     11.438  0.2295E-02  0.2295E-02  0.3723E-01  0.3723E-01
     11.552  0.4356E-02  0.4356E-02  0.3773E-01  0.3773E-01
     11.666  0.2131E-02  0.2131E-02  0.3798E-01  0.3798E-01
     11.781  0.9976E-03  0.9976E-03  0.3809E-01  0.3809E-01
     11.895  0.1186E-02  0.1186E-02  0.3823E-01  0.3823E-01
     12.010  0.1871E-02  0.1871E-02  0.3844E-01  0.3844E-01
     12.124  0.2196E-02  0.2196E-02  0.3869E-01  0.3869E-01
     12.238  0.2120E-02  0.2120E-02  0.3893E-01  0.3893E-01
     12.353  0.1541E-02  0.1541E-02  0.3911E-01  0.3911E-01
     12.467  0.1588E-02  0.1588E-02  0.3929E-01  0.3929E-01
     12.582  0.1451E-02  0.1451E-02  0.3946E-01  0.3946E-01
     12.696  0.1607E-02  0.1607E-02  0.3964E-01  0.3964E-01
     12.810  0.1127E-02  0.1127E-02  0.3977E-01  0.3977E-01
     12.925  0.8882E-03  0.8882E-03  0.3987E-01  0.3987E-01
     13.039  0.2257E-02  0.2257E-02  0.4013E-01  0.4013E-01
     13.154  0.2087E-02  0.2087E-02  0.4037E-01  0.4037E-01
     13.268  0.1577E-02  0.1577E-02  0.4055E-01  0.4055E-01
     13.382  0.1897E-02  0.1897E-02  0.4077E-01  0.4077E-01
     13.497  0.1811E-02  0.1811E-02  0.4097E-01  0.4097E-01
     13.611  0.1720E-02  0.1720E-02  0.4117E-01  0.4117E-01
     13.726  0.1704E-02  0.1704E-02  0.4137E-01  0.4137E-01
     13.840  0.2673E-02  0.2673E-02  0.4167E-01  0.4167E-01
     13.954  0.2341E-02  0.2341E-02  0.4194E-01  0.4194E-01
     14.069  0.2798E-02  0.2798E-02  0.4226E-01  0.4226E-01
     14.183  0.1639E-02  0.1639E-02  0.4245E-01  0.4245E-01
     14.297  0.2797E-02  0.2797E-02  0.4277E-01  0.4277E-01
     14.412  0.2822E-02  0.2822E-02  0.4309E-01  0.4309E-01
     14.526  0.1561E-02  0.1561E-02  0.4327E-01  0.4327E-01
     14.641  0.1993E-02  0.1993E-02  0.4350E-01  0.4350E-01
     14.755  0.2066E-02  0.2066E-02  0.4373E-01  0.4373E-01
     14.869  0.1793E-02  0.1793E-02  0.4394E-01  0.4394E-01
     14.984  0.1399E-02  0.1399E-02  0.4410E-01  0.4410E-01
     15.098  0.1854E-02  0.1854E-02  0.4431E-01  0.4431E-01
     15.213  0.2441E-02  0.2441E-02  0.4459E-01  0.4459E-01
     15.327  0.3267E-02  0.3267E-02  0.4496E-01  0.4496E-01
     15.441  0.2247E-02  0.2247E-02  0.4522E-01  0.4522E-01
     15.556  0.1550E-02  0.1550E-02  0.4540E-01  0.4540E-01
     15.670  0.1076E-02  0.1076E-02  0.4552E-01  0.4552E-01
     15.785  0.1688E-02  0.1688E-02  0.4571E-01  0.4571E-01
     15.899  0.3053E-02  0.3053E-02  0.4606E-01  0.4606E-01
     16.013  0.2228E-02  0.2228E-02  0.4632E-01  0.4632E-01
     16.128  0.1821E-02  0.1821E-02  0.4653E-01  0.4653E-01
     16.242  0.1826E-02  0.1826E-02  0.4673E-01  0.4673E-01
     16.357  0.1995E-02  0.1995E-02  0.4696E-01  0.4696E-01
     16.471  0.2034E-02  0.2034E-02  0.4720E-01  0.4720E-01
     16.585  0.1912E-02  0.1912E-02  0.4741E-01  0.4741E-01
     16.700  0.2632E-02  0.2632E-02  0.4771E-01  0.4771E-01
     16.814  0.1805E-02  0.1805E-02  0.4792E-01  0.4792E-01
     16.929  0.2035E-02  0.2035E-02  0.4815E-01  0.4815E-01
     17.043  0.1952E-02  0.1952E-02  0.4838E-01  0.4838E-01
     17.157  0.1668E-02  0.1668E-02  0.4857E-01  0.4857E-01
     17.272  0.9214E-03  0.9214E-03  0.4867E-01  0.4867E-01
     17.386  0.8976E-03  0.8976E-03  0.4878E-01  0.4878E-01
     17.501  0.6501E-03  0.6501E-03  0.4885E-01  0.4885E-01
     17.615  0.7981E-03  0.7981E-03  0.4894E-01  0.4894E-01
     17.729  0.7348E-03  0.7348E-03  0.4903E-01  0.4903E-01
     17.844  0.1090E-02  0.1090E-02  0.4915E-01  0.4915E-01
     17.958  0.6298E-03  0.6298E-03  0.4922E-01  0.4922E-01
     18.072  0.1010E-02  0.1010E-02  0.4934E-01  0.4934E-01
     18.187  0.1149E-02  0.1149E-02  0.4947E-01  0.4947E-01
     18.301  0.5932E-03  0.5932E-03  0.4954E-01  0.4954E-01
     18.416  0.4829E-03  0.4829E-03  0.4959E-01  0.4959E-01
     18.530  0.1504E-02  0.1504E-02  0.4976E-01  0.4976E-01
     18.644  0.9402E-03  0.9402E-03  0.4987E-01  0.4987E-01
     18.759  0.7189E-03  0.7189E-03  0.4995E-01  0.4995E-01
     18.873  0.9444E-03  0.9444E-03  0.5006E-01  0.5006E-01
     18.988  0.7852E-03  0.7852E-03  0.5015E-01  0.5015E-01
     19.102  0.7230E-03  0.7230E-03  0.5024E-01  0.5024E-01
     19.216  0.6667E-03  0.6667E-03  0.5031E-01  0.5031E-01
     19.331  0.9851E-03  0.9851E-03  0.5042E-01  0.5042E-01
     19.445  0.1583E-02  0.1583E-02  0.5061E-01  0.5061E-01
     19.560  0.8028E-03  0.8028E-03  0.5070E-01  0.5070E-01
     19.674  0.9239E-03  0.9239E-03  0.5080E-01  0.5080E-01
     19.788  0.9916E-03  0.9916E-03  0.5092E-01  0.5092E-01
     19.903  0.1340E-02  0.1340E-02  0.5107E-01  0.5107E-01
     20.017  0.1431E-02  0.1431E-02  0.5123E-01  0.5123E-01
     20.132  0.1074E-02  0.1074E-02  0.5136E-01  0.5136E-01
     20.246  0.1479E-02  0.1479E-02  0.5153E-01  0.5153E-01
     20.360  0.1907E-02  0.1907E-02  0.5174E-01  0.5174E-01
     20.475  0.1082E-02  0.1082E-02  0.5187E-01  0.5187E-01
     20.589  0.4779E-03  0.4779E-03  0.5192E-01  0.5192E-01
     20.704  0.1108E-02  0.1108E-02  0.5205E-01  0.5205E-01
     20.818  0.2028E-02  0.2028E-02  0.5228E-01  0.5228E-01
     20.932  0.1677E-02  0.1677E-02  0.5247E-01  0.5247E-01
     21.047  0.1045E-02  0.1045E-02  0.5259E-01  0.5259E-01
     21.161  0.2156E-02  0.2156E-02  0.5284E-01  0.5284E-01
     21.275  0.1684E-02  0.1684E-02  0.5303E-01  0.5303E-01
     21.390  0.1393E-02  0.1393E-02  0.5319E-01  0.5319E-01
     21.504  0.1013E-02  0.1013E-02  0.5331E-01  0.5331E-01
     21.619  0.1578E-02  0.1578E-02  0.5349E-01  0.5349E-01
     21.733  0.1678E-02  0.1678E-02  0.5368E-01  0.5368E-01
     21.847  0.1329E-02  0.1329E-02  0.5383E-01  0.5383E-01
     21.962  0.1767E-02  0.1767E-02  0.5403E-01  0.5403E-01
     22.076  0.1304E-02  0.1304E-02  0.5418E-01  0.5418E-01
     22.191  0.1466E-02  0.1466E-02  0.5435E-01  0.5435E-01
     22.305  0.1303E-02  0.1303E-02  0.5450E-01  0.5450E-01
     22.419  0.2323E-02  0.2323E-02  0.5476E-01  0.5476E-01
     22.534  0.2154E-02  0.2154E-02  0.5501E-01  0.5501E-01
     22.648  0.1909E-02  0.1909E-02  0.5523E-01  0.5523E-01
     22.763  0.2196E-02  0.2196E-02  0.5548E-01  0.5548E-01
     22.877  0.1566E-02  0.1566E-02  0.5566E-01  0.5566E-01
     22.991  0.1669E-02  0.1669E-02  0.5585E-01  0.5585E-01
     23.106  0.2335E-02  0.2335E-02  0.5612E-01  0.5612E-01
     23.220  0.1886E-02  0.1886E-02  0.5633E-01  0.5633E-01
     23.335  0.2302E-02  0.2302E-02  0.5660E-01  0.5660E-01
     23.449  0.2461E-02  0.2461E-02  0.5688E-01  0.5688E-01
     23.563  0.2222E-02  0.2222E-02  0.5713E-01  0.5713E-01
     23.678  0.1923E-02  0.1923E-02  0.5735E-01  0.5735E-01
     23.792  0.1679E-02  0.1679E-02  0.5754E-01  0.5754E-01
     23.907  0.1505E-02  0.1505E-02  0.5772E-01  0.5772E-01
     24.021  0.1611E-02  0.1611E-02  0.5790E-01  0.5790E-01
     24.135  0.1818E-02  0.1818E-02  0.5811E-01  0.5811E-01
     24.250  0.1459E-02  0.1459E-02  0.5828E-01  0.5828E-01
     24.364  0.1587E-02  0.1587E-02  0.5846E-01  0.5846E-01
     24.478  0.1991E-02  0.1991E-02  0.5869E-01  0.5869E-01
     24.593  0.2785E-02  0.2790E-02  0.5900E-01  0.5900E-01
     24.707  0.9051E-03  0.9071E-03  0.5911E-01  0.5911E-01
     24.822  0.6939E-03  0.6870E-03  0.5919E-01  0.5919E-01
     24.936  0.1250E-02  0.1243E-02  0.5933E-01  0.5933E-01
     25.050  0.1641E-02  0.1625E-02  0.5952E-01  0.5951E-01
     25.165  0.4307E-03  0.4544E-03  0.5957E-01  0.5957E-01
     25.279  0.3112E-03  0.3101E-03  0.5960E-01  0.5960E-01
     25.394  0.6154E-03  0.6153E-03  0.5967E-01  0.5967E-01
     25.508  0.7665E-03  0.7665E-03  0.5976E-01  0.5976E-01
     25.622  0.8797E-03  0.8789E-03  0.5986E-01  0.5986E-01
     25.737  0.4103E-03  0.4109E-03  0.5991E-01  0.5991E-01
     25.851  0.3430E-03  0.3432E-03  0.5995E-01  0.5995E-01
     25.966  0.1010E-03  0.1010E-03  0.5996E-01  0.5996E-01
     26.080  0.5076E-04  0.5077E-04  0.5996E-01  0.5996E-01
     26.194  0.3496E-04  0.3487E-04  0.5997E-01  0.5997E-01
     26.309  0.8432E-04  0.8303E-04  0.5998E-01  0.5998E-01
     26.423  0.1887E-03  0.1901E-03  0.6000E-01  0.6000E-01
     26.538  0.4773E-05  0.4718E-05  0.6000E-01  0.6000E-01
     26.652 -0.2351E-05 -0.2360E-05  0.6000E-01  0.6000E-01
     26.766 -0.1592E-07 -0.1583E-07  0.6000E-01  0.6000E-01
     26.881 -0.6166E-11 -0.6084E-11  0.6000E-01  0.6000E-01
     26.995 -0.1586E-15 -0.1555E-15  0.6000E-01  0.6000E-01
     27.110  0.0000E+00  0.0000E+00  0.6000E-01  0.6000E-01
     27.224  0.0000E+00  0.0000E+00  0.6000E-01  0.6000E-01
     27.338  0.0000E+00  0.0000E+00  0.6000E-01  0.6000E-01
     27.453  0.0000E+00  0.0000E+00  0.6000E-01  0.6000E-01
     27.567  0.0000E+00  0.0000E+00  0.6000E-01  0.6000E-01
     27.682  0.0000E+00  0.0000E+00  0.6000E-01  0.6000E-01
     27.796  0.0000E+00  0.0000E+00  0.6000E-01  0.6000E-01
     27.910  0.0000E+00  0.0000E+00  0.6000E-01  0.6000E-01

**Comment by bjmorgan** [comment] 2020-07-07 08:37
Your DOSCAR doesn’t contain any projected densities of states, so `read_projected_dos()` fails. 

I suspect you need to set `LORBIT` in your `INCAR`
https://www.vasp.at/wiki/index.php/DOSCAR

**Comment by bjmorgan** [comment] 2021-08-09 10:46
Closing here, as this issue is covered by https://github.com/bjmorgan/vasppy/issues/14.

**Closed by bjmorgan** 2021-08-09 10:46 UTC
